Pnast/feature/mic 5678 parallel tests
ihmeuw/vivarium_build_utils pull request #12
Opened 2024-12-27 17:53 UTC by patricktnast

## Title: Summary, imperative, start upper case, don't end with a period

### Description

- *Category*: 
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-XYZ

### Changes and notes
 

### Testing

2024-12-27 21:19 UTC, stevebachmeier requested changes
I think the parallel stages might break python matrix.

2024-12-27 21:19 UTC, stevebachmeier commented on vars/reusable_pipeline.groovy
> +                        ["${full_name(it)} Tests" : {
What in the world is `it`? Is that some silly groovy thing?

2024-12-27 21:19 UTC, stevebachmeier commented on vars/reusable_pipeline.groovy
> +                    def parallelStages = test_types.collectEntries {
Is this going to create Jenkins a `ParallelStage`? If so, I think that's going to eventually cause a problem when we implement the python matrix here

2024-12-27 21:19 UTC, stevebachmeier commented on vars/reusable_pipeline.groovy
> +                                sh "${ACTIVATE} && make ${it}"
I see, so this is all relying on us defining the different test types w/in each makefile (i.e. whether "integration" means --runslow, or run some specific folder of tests, or runs tests marked as integration, etc etc). I like it.

2024-12-27 21:56 UTC, patricktnast commented on vars/reusable_pipeline.groovy
> +                    def parallelStages = test_types.collectEntries {
I was worried about this too, but this already has a python matrix and it seems to work. I think it would just run them concurrently on the same node instead of breaking them into different nodes

2024-12-27 21:56 UTC, patricktnast commented on vars/reusable_pipeline.groovy
> +                        ["${full_name(it)} Tests" : {
https://stackoverflow.com/questions/54902509/what-is-the-groovy-it

2024-12-27 22:25 UTC, patricktnast commented on vars/reusable_pipeline.groovy
> +                    def parallelStages = test_types.collectEntries {
(I say "would" because I only tested this with vivarium, which only has a integration section in its makefile)

2024-12-30 18:11 UTC, rmudambi approved these changes

2024-12-30 18:11 UTC, rmudambi commented on vars/reusable_pipeline.groovy
> +                    def full_name = { test_type ->
Does this have to be defined as a closure? Why can't you just define it as a normal function - i.e.
```groovy
def full_name(test_type) {
    if (test_type == 'e2e') {
        return "End-to-End"
    } else {
        return test_type.capitalize()
    }
}
```

2024-12-30 20:08 UTC, stevebachmeier approved these changes
Approving with the caveat that you recognize we may have issues w/ Parallel vs build matrix later

2025-01-02 17:39 UTC, albrja approved these changes

2025-01-03 17:40 UTC, patricktnast commented on vars/reusable_pipeline.groovy
> +                    def full_name = { test_type ->
you'd have to define it outside of the call() at the top, which I didn't like

2025-01-03 20:26 UTC, closed without merging